name: Publish

on:
  push:
    branches:
        - kp-rtd-sphinx-reorg

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        sudo apt-get install -y python3-setuptools
        pip3 install --user -r requirements.txt
    - name: Build the docs
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        make html
    - name: Deploy the docs
      run: |
        mkdir $HOME/output
        mv _output/html $HOME/output/latest
        touch $HOME/output/.nojekyll
        mv docs/html/index2.html $HOME/output/index.html
        cd $HOME/output
        git init
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@github.com"
        git add .
        git commit -m "latest html output"
        git push -f https://${GITHUB_ACTOR}:${{secrets.ACCESS_TOKEN}}@github.com/intelkevinputnam/pmem-csi.git HEAD:gh-pages
